//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperations.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Product
    {
        [Required(ErrorMessage = "Can't leave the field empty.")]
        
        public int Productid { get; set; }
        [Required(ErrorMessage = "Can't leave the field empty.")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Can't leave the field empty.")]
        public string Brand { get; set; }
        [Required(ErrorMessage = "Can't leave the field empty.")]
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Can't leave the field empty.")]
        public bool Status { get; set; }
    }
}
